---
title: "CV"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  markdown: 
    wrap: 72
---

### EDUCATION 

**Columbia University, Mailman School of Public Health** <br /> (Expected) *Graduation Spring 2026*
<br /> Masters of Science in Biostatistics, Concentration in Statistical Genetics

**UC Berkeley, College of Chemistry** <br /> *Graduation Spring 2023*
<br /> Bachelor of Science in Chemical Biology, Minor in Data Science

### SKILLS

**Technical:**
<br />Proficient in SQL, Python, Tableau, and R and
using Seurat, SoupX, and Plotly libraries

### PROFESSIONAL EXPERIENCE

**Seoul National University - Lab of Immune Tolerance**
<br />*Jun 2024 - Aug 2024* | Research Intern | Seoul, South Korea  
&nbsp; &nbsp;• Analyzed single-cell RNA sequencing (scRNA-seq) data from patient skin
lesions pre-treatment, during treatment, and post-treatment for psoriasis
<br />&nbsp; &nbsp;• Optimized pipeline code to process and analyze large-scale scRNA-seq
data, identifying key transcriptional changes across treatment stage
<br />&nbsp; &nbsp;• Improved pipeline usability and reproducibility, reducing the setup
time by 10% through modular coding and documentation enhancements.

**Genentech**
<br /> *Jun 2023 - Jun 2024* | Research Associate I | South San Francisco, CA
<br />&nbsp; &nbsp;• Determined BrdU activation of peripheral blood mononuclear cells
(PBMCs) for 100+ novel drugs to evaluate immunogenicity risk
<br />&nbsp; &nbsp;• Employed single-cell genomic profiling techniques to investigate
cellular drug response, identifying novel drug-target interactions and
potential biomarkers
<br />&nbsp; &nbsp;• Conducted ELISPOT assays to assess cellular immune responses, providing valuable insights into CD4 T-cell proliferation and cytokine production in response to novel drugs
<br />&nbsp; &nbsp;• Refined a standardized PBMC isolation protocol to consistently yield
high-quality cell populations, achieving a 95% success rate and viability
<br />&nbsp; &nbsp;• Developed and implemented custom automation scripts that streamlined
data processing, analysis, and reporting processes

**Samsung Bioepis, Inc.**
<br />*Jul 2022— Aug 2022* | MSAT Manufacturing Science 2 Intern | Incheon, South Korea 
<br />&nbsp; &nbsp;• Coordinating in the design and execution of process characterization
and validation studies abiding by cGMP and SOPs
<br />&nbsp; &nbsp;• Assisted in laboratory operations, including buffer and chromatography column preparation, analytical equipment maintenance, and purification performance observation
<br />&nbsp; &nbsp;• Programmed on UNICORN software to design column-specific methodology
to optimize monoclonal antibodies yield on AKTA chromatography systems
<br />&nbsp; &nbsp;• Conducted extensive literature review in troubleshooting low yields of expired resin to elongate its lifetime for cost-effective usage.

**Miller Lab, UC Berkeley**
<br />*Aug 2021— Dec 2022* | Research Assistant | Berkeley, CA
<br />&nbsp; &nbsp;• Developed Python code to automate photon counting for cardiomyocytes, enabling the extraction of valuable Fluorescence Lifetime Imaging Microscopy (FLIM) data
<br />&nbsp; &nbsp;• Developed the workflow for the initial synthesis of liposomes,
enabling the exploration of lipid composition’s effect on the behavior of fluorescent dyes
<br />&nbsp; &nbsp;• Performed qualitative characterization of liposome using an inverted microscope and conducted in-depth analysis of their fluorescence lifetime
<br />&nbsp; &nbsp;• Utilized Dynamic Light Scattering (DLS) to ensure data consistency in the comprehensive characterization of liposomes

**Fellowship Proposal** | General Biochemistry and Molecular Biology | *UC Berkeley*
<br />*Conservation of functionality in Cin8 between Chaetomium thermophilum
and Saccharomyces cerevisiae for future cancer research*
<br />&nbsp; &nbsp;• Conducted molecular cloning, PCR, cell culture, western-blot, protein purification, and selection of yeast Cin8p, followed by characterization with analytical in vitro and in vivo assays, including ATPase assay, NADH assay, affinity chromatography, and fluorescent imaging to track the localization of GFP labeled constructs
<br />&nbsp; &nbsp;• Performed literature search to design hypotheses and experiments to testify Cin8p’s structural and functional conservation across species and utilized collected data for analysis report and mock-grant proposal.

### LEADERSHIP

**Project Manager | Species Frontal Lobe Size Prediction Model** 
<br />*Jan 2023 - May 2023*
<br />&nbsp; &nbsp;• Made critical decisions on model development approaches and variable
selection, resulting in a final predictive model with 90% accuracy
<br />&nbsp; &nbsp;• Demonstrated adaptability to evolving project requirements and embraced feedback from team members, resulting in successful model iterations and improvements
<br />&nbsp; &nbsp;• Delivered engaging presentations and comprehensive reports on the model development process and findings
<br />&nbsp; &nbsp;• Fostered effective communication and teamwork to integrate expertise
and achieve an accurate predictive model

**Project Manager | Philippines Nutritional Inadequacy Identification**
<br />*Jan 2023 - May 2023* | [GitHub](https://github.com/lizchoi918/indp_project)
<br />&nbsp; &nbsp;• Spearheaded a multidisciplinary team in conducting a comprehensive needs assessment, meticulously identifying prevalent nutritional deficiencies in the Bukidnon region, Philippines
<br />&nbsp; &nbsp;• Analyzed and interpreted the collected data, unveiling actionable insights to inform targeted interventions
<br />&nbsp; &nbsp;• Orchestrated the design and implementation of sustainable nutrition
education programs, tailored to address the distinctive needs of vulnerable groups
<br />&nbsp; &nbsp;• Conducted periodic project assessments to quantitatively measure impact and discern areas for continuous refinement

**Alzheimer’s Association** 
<br /> *Dec 2019 – Nov 2022* | Member/Volunteer | Berkeley, CA
<br />&nbsp; &nbsp;• Actively participated and successfully raised \$663 in the annual Walk to End Alzheimer’s in San Francisco, supporting dementia patients and advancing research efforts aimed at treatment and prevention
<br />&nbsp; &nbsp;• Organized and participated in 10+ monthly volunteer visits to the local nursing home, fostering meaningful connections with residents and improving overall resident well-being

**American Chemical Society** 
<br />*Aug 2020—Aug 2021* | Media Committee Member | Berkeley, CA
<br />&nbsp; &nbsp;• Coordinated career development work for 30+ networking events to support professional development of 100+ ACS members
<br />&nbsp; &nbsp;• Engaged with club members, faculty, and potential attendees during events, fostering strong relationships and expanding the club's network, resulting in a 10% increase in event partnerships with other academic organizations
<br />&nbsp; &nbsp;• Coordinated event campaigns within strict deadlines, ensuring all promotional materials were delivered on time, resulting in a 100% on-time campaign delivery rate
<br />&nbsp; &nbsp;• Made data-driven decisions on campaign target audiences and promotional channels, leading to a 15% increase in event attendance from the previous year
