---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r, echo = FALSE, message = FALSE}
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

```{r, message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") %>% 
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  separate(date, c("year","month","day"), sep = "-") %>% 
  select(name, id, everything())
```

### Chart A

```{r, message = FALSE}
weather_df %>%
  mutate(text_label = str_c("Minimum Temperature: ", tmin, " Maximum Temperature: ", tmax)) %>% 
  plot_ly(
    x= ~tmin, y= ~tmax, color = ~name, text= ~text_label, alpha = 0.5, type = "scatter", mode = "markers", colors= "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, message = FALSE}
weather_df %>% 
  mutate(name = fct_reorder(name, tmax), na_rm = TRUE) %>% 
  plot_ly(y= ~tmax, x= ~name, type = "box", color = ~name, colors = "viridis")
```

### Chart C

```{r, message = FALSE}
weather_df %>% 
  mutate(date_prcp = str_c("Month: ", month, " Precipitation: ", prcp)) %>% plot_ly(
    x = ~month, y= ~prcp, color = ~name, text = ~date_prcp, type = "bar", colors = "viridis")
```

